export const missions = [
  {
    missionId: 'construction-site-trespass',
    title: 'Construction Site: Trespass or Escalation?',
    manualTopic: 'Trespassing and Vandalism',
    difficulty: 'Medium',
    estimatedTime: '4 minutes',
    skills: ['Observation', 'Access Control', 'Police Notification', 'Escalation Judgment', 'Documentation'],
    startScene: 'scene-security-post',
    scenes: [
      {
        sceneId: 'scene-security-post',
        background: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1600&q=80',
        narration: 'You are posted at a construction site during a night shift. Your responsibility is to protect the property and control access.',
        hotspots: [{ id: 'start-patrol', label: 'Start Patrol', nextScene: 'scene-fence-line' }],
      },
      {
        sceneId: 'scene-fence-line',
        background: 'https://images.unsplash.com/photo-1581093458791-9f3c3900df4b?auto=format&fit=crop&w=1600&q=80',
        narration: 'While patrolling near the materials area, you notice an unauthorized person inside the fence.',
        dialogue: "You: 'This is private property. Please leave the site.' Person: 'Relax. I am not doing anything.'",
        question: 'What should you do first?',
        manualPrinciple: 'Trespassers should generally be asked to leave first while maintaining safety.',
        choices: [
          {
            choiceId: 'A',
            text: 'Immediately run toward the person and tackle them.',
            isCorrect: false,
            nextScene: 'scene-refuses-to-leave',
            consequence: 'The person panics and resists. The situation becomes unsafe.',
            riskScores: { legalRisk: 90, safetyRisk: 95, professionalism: 20, situationControl: 15, documentationReadiness: 20 },
            manualFeedback: 'The situation has not escalated yet. Ask to leave and observe from a safe distance first.',
          },
          {
            choiceId: 'B',
            text: 'Ask the person to leave and observe from a safe distance.',
            isCorrect: true,
            nextScene: 'scene-refuses-to-leave',
            consequence: 'You maintain control without escalating the situation.',
            riskScores: { legalRisk: 10, safetyRisk: 15, professionalism: 90, situationControl: 85, documentationReadiness: 70 },
            manualFeedback: 'This matches the recommended first response for a trespasser.',
          },
          {
            choiceId: 'C',
            text: 'Ignore the person unless damage starts.',
            isCorrect: false,
            nextScene: 'scene-refuses-to-leave',
            consequence: 'The unauthorized person continues moving around the site unchecked.',
            riskScores: { legalRisk: 55, safetyRisk: 65, professionalism: 30, situationControl: 25, documentationReadiness: 30 },
            manualFeedback: 'Ignoring unauthorized access reduces site control and can increase risk.',
          },
          {
            choiceId: 'D',
            text: 'Search the person bag immediately.',
            isCorrect: false,
            nextScene: 'scene-refuses-to-leave',
            consequence: 'The person becomes defensive and challenges your authority.',
            riskScores: { legalRisk: 92, safetyRisk: 80, professionalism: 15, situationControl: 20, documentationReadiness: 25 },
            manualFeedback: 'Improper search creates legal risk and can escalate conflict.',
          },
        ],
      },
      {
        sceneId: 'scene-refuses-to-leave',
        background: 'https://images.unsplash.com/photo-1519003722824-194d4455a60c?auto=format&fit=crop&w=1600&q=80',
        narration: 'The person refuses to leave and continues walking around the site.',
        question: 'What should you do next?',
        manualPrinciple: 'If trespasser refuses lawful direction, call police and continue observation.',
        choices: [
          {
            choiceId: 'A',
            text: 'Call police and continue observing from a safe distance.',
            isCorrect: true,
            nextScene: 'scene-escalation-vandalism',
            consequence: 'You maintain safety while waiting for assistance.',
            riskScores: { legalRisk: 15, safetyRisk: 20, professionalism: 92, situationControl: 88, documentationReadiness: 75 },
            manualFeedback: 'Correct response. Escalate through police while preserving safety.',
          },
          {
            choiceId: 'B',
            text: 'Physically remove the person yourself.',
            isCorrect: false,
            nextScene: 'scene-escalation-vandalism',
            consequence: 'The person becomes aggressive. Safety risk increases.',
            riskScores: { legalRisk: 88, safetyRisk: 90, professionalism: 20, situationControl: 20, documentationReadiness: 35 },
            manualFeedback: 'Physical intervention may create unnecessary danger in this situation.',
          },
          {
            choiceId: 'C',
            text: 'Leave the site because they refused to listen.',
            isCorrect: false,
            nextScene: 'scene-escalation-vandalism',
            consequence: 'Site is left unsecured and incident worsens.',
            riskScores: { legalRisk: 70, safetyRisk: 85, professionalism: 10, situationControl: 5, documentationReadiness: 10 },
            manualFeedback: 'Abandoning post is unsafe and unprofessional.',
          },
          {
            choiceId: 'D',
            text: 'Let them stay if they are not touching anything.',
            isCorrect: false,
            nextScene: 'scene-escalation-vandalism',
            consequence: 'Unauthorized access continues and control is lost.',
            riskScores: { legalRisk: 62, safetyRisk: 75, professionalism: 25, situationControl: 15, documentationReadiness: 20 },
            manualFeedback: 'Unauthorized presence still requires response and reporting.',
          },
        ],
      },
      {
        sceneId: 'scene-escalation-vandalism',
        background: 'https://images.unsplash.com/photo-1565043666747-69f6646db940?auto=format&fit=crop&w=1600&q=80',
        narration: 'While waiting for police, the person picks up metal and breaks a trailer window.',
        question: 'The situation has escalated. What should you do?',
        manualPrinciple: 'Update police immediately, continue safe observation, and document escalation details.',
        choices: [
          {
            choiceId: 'A',
            text: 'Update police immediately, observe, record details, and assess safety.',
            isCorrect: true,
            nextScene: 'scene-documentation',
            consequence: 'You keep yourself safe and provide updated incident details.',
            riskScores: { legalRisk: 10, safetyRisk: 20, professionalism: 95, situationControl: 90, documentationReadiness: 90 },
            manualFeedback: 'Correct. Incident has escalated to vandalism and requires updated reporting.',
          },
          {
            choiceId: 'B',
            text: 'Ignore the damage because police are already coming.',
            isCorrect: false,
            nextScene: 'scene-documentation',
            consequence: 'Important escalation details are lost and response quality drops.',
            riskScores: { legalRisk: 65, safetyRisk: 70, professionalism: 30, situationControl: 25, documentationReadiness: 20 },
            manualFeedback: 'Escalation details must be reported and documented in real time.',
          },
          {
            choiceId: 'C',
            text: 'Run in immediately and fight the person.',
            isCorrect: false,
            nextScene: 'scene-documentation',
            consequence: 'You create high personal danger and increase confrontation risk.',
            riskScores: { legalRisk: 90, safetyRisk: 96, professionalism: 15, situationControl: 20, documentationReadiness: 25 },
            manualFeedback: 'Unsafe confrontation can worsen injury and liability risk.',
          },
          {
            choiceId: 'D',
            text: 'Leave without recording anything.',
            isCorrect: false,
            nextScene: 'scene-documentation',
            consequence: 'No continuity of information is available for police and supervisor.',
            riskScores: { legalRisk: 75, safetyRisk: 80, professionalism: 8, situationControl: 10, documentationReadiness: 5 },
            manualFeedback: 'Leaving and not documenting fails core observe-report duties.',
          },
        ],
      },
      {
        sceneId: 'scene-documentation',
        background: 'https://images.unsplash.com/photo-1516900557549-41557d405adf?auto=format&fit=crop&w=1600&q=80',
        narration: 'Police arrive and your supervisor asks you to complete notes.',
        question: 'What should your notes include?',
        manualPrinciple: 'Notes must be factual, objective, detailed, and time-based.',
        choices: [
          {
            choiceId: 'A',
            text: 'Time, location, description, observations, actions, call time, and police arrival.',
            isCorrect: true,
            nextScene: null,
            consequence: 'Your notes are complete and useful.',
            riskScores: { legalRisk: 15, safetyRisk: 10, professionalism: 92, situationControl: 88, documentationReadiness: 98 },
            manualFeedback: 'Accurate objective notes support investigations and legal review.',
          },
          {
            choiceId: 'B',
            text: 'The person was obviously a criminal.',
            isCorrect: false,
            nextScene: null,
            consequence: 'Opinion-based notes weaken professionalism and reliability.',
            riskScores: { legalRisk: 78, safetyRisk: 30, professionalism: 20, situationControl: 35, documentationReadiness: 20 },
            manualFeedback: 'Use facts, not conclusions or emotional language.',
          },
          {
            choiceId: 'C',
            text: 'Only the fact that police arrived.',
            isCorrect: false,
            nextScene: null,
            consequence: 'Report is incomplete and lacks incident context.',
            riskScores: { legalRisk: 60, safetyRisk: 25, professionalism: 45, situationControl: 50, documentationReadiness: 25 },
            manualFeedback: 'Complete timeline and observed behavior are required.',
          },
          {
            choiceId: 'D',
            text: 'Nothing, because police handled it.',
            isCorrect: false,
            nextScene: null,
            consequence: 'No record exists for employer review or court reference.',
            riskScores: { legalRisk: 72, safetyRisk: 30, professionalism: 10, situationControl: 15, documentationReadiness: 5 },
            manualFeedback: 'Security duties include objective documentation even after police involvement.',
          },
        ],
      },
    ],
  },
  {
    missionId: 'retail-shoplifting',
    title: 'Retail Store: Reported Shoplifting',
    manualTopic: 'Observation and Legal Caution',
    difficulty: 'Medium',
    estimatedTime: '2 minutes',
    skills: ['Observation', 'Policy Compliance'],
    startScene: 'retail-step-1',
    scenes: [
      {
        sceneId: 'retail-step-1',
        background: 'construction-site-gate-night.png',
        narration: 'An employee reports a possible theft near exit.',
        question: 'What do you do first?',
        manualPrinciple: 'Gather facts and observe before escalating.',
        choices: [
          {
            choiceId: 'B',
            text: 'Ask employee what they saw, observe, and follow policy.',
            isCorrect: true,
            nextScene: null,
            consequence: 'You apply safe observe-report procedure.',
            riskScores: { legalRisk: 10, safetyRisk: 15, professionalism: 90, situationControl: 80, documentationReadiness: 80 },
            manualFeedback: 'Strong legal and professional response.',
          },
        ],
      },
    ],
  },
  {
    missionId: 'angry-visitor',
    title: 'Front Desk: Angry Visitor',
    manualTopic: 'Communication and De-escalation',
    difficulty: 'Medium',
    estimatedTime: '2 minutes',
    skills: ['Communication', 'De-escalation'],
    startScene: 'visitor-step-1',
    scenes: [
      {
        sceneId: 'visitor-step-1',
        background: 'construction-site-gate-night.png',
        narration: 'Visitor denied access starts yelling at front desk.',
        question: 'What is the best first response?',
        manualPrinciple: 'Stay calm, keep distance, and communicate policy clearly.',
        choices: [
          {
            choiceId: 'B',
            text: 'Stay calm, keep distance, and explain access policy.',
            isCorrect: true,
            nextScene: null,
            consequence: 'Escalation risk is reduced.',
            riskScores: { legalRisk: 10, safetyRisk: 15, professionalism: 95, situationControl: 85, documentationReadiness: 70 },
            manualFeedback: 'Correct de-escalation response.',
          },
        ],
      },
    ],
  },
];
